const projects = [
    {
        "title": "AI_Manga_Reader",
        "full_name": "VrajVyas11/AI_Manga_Reader",
        "githubLink": "https://github.com/VrajVyas11/AI_Manga_Reader",
        "description": "AI Manga Reader is a next-gen manga app powered by the MangaDex API, offering vast multi-language content and flexible reading modes. It uses AI-powered OCR to extract and translate text from manga pages, combined with AI-driven text-to-speech narration—letting you effortlessly read and listen to any chapter or page, anytime, anywhere.",
        "created_at": "2025-01-12T11:44:38Z",
        "updated_at": "2025-07-03T17:05:22Z",
        "pushed_at": "2025-07-03T17:05:19Z",
        "language": "JavaScript",
        "stargazers_count": 17,
        "forks_count": 11,
        "tags": [
            "manga",
            "manga-reader",
            "manga-search",
            "mangadex",
            "mangadex-api",
            "mangareader",
            "manhua",
            "manhua-reader",
            "manhwa",
            "manhwa-reader",
            "ocr",
            "scraping",
            "scraping-websites",
            "tta",
            "tts",
            "webscraping"
        ],
        "liveLink": "https://ai-manga-reader.onrender.com/",
        "image": "/manga.png",
        "default_branch": "main"
    },
    {
        "title": "PDF-Manipulator",
        "full_name": "VrajVyas11/PDF-Manipulator",
        "githubLink": "https://github.com/VrajVyas11/PDF-Manipulator",
        "description": "A comprehensive PDF tool that allows you to effortlessly edit, merge, split, compress, and convert PDFs. It supports adding pages, extracting images, and viewing PDFs directly within the app. With a user-friendly drag-and-drop interface, it’s fully responsive across all devices, streamlining document management for everyone.",
        "created_at": "2024-10-11T12:56:13Z",
        "updated_at": "2025-05-20T12:10:31Z",
        "pushed_at": "2025-05-15T12:35:01Z",
        "language": "JavaScript",
        "stargazers_count": 7,
        "forks_count": 2,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit"
        },
        "liveLink": "https://pdf-manipulator-gdqt.onrender.com/",
        "image": "/pdf.png",
        "tags": [
            "add-page",
            "docx-pdf-converstion",
            "image-to-pdf",
            "pdf",
            "pdf-compressor",
            "pdf-document-processor",
            "pdf-download",
            "pdf-editor",
            "pdf-image-extractor",
            "pdf-manipulation",
            "pdf-merger",
            "pdf-viewer",
            "split-pdf",
            "word-pdf"
        ],
        "default_branch": "main"
    },
    {
        "title": "React_Windows_11",
        "full_name": "VrajVyas11/React_Windows_11",
        "githubLink": "https://github.com/VrajVyas11/React_Windows_11",
        "description": "This React project is a Windows 11 clone featuring draggable windows for apps like Chrome, VS Code, and Calculator. It includes a working Start Menu, search, shutdown, restart, login page, right-click context menu, and terminal. Built with React, Tailwind CSS, and Framer Motion for smooth animations. No external draggable libraries used.",
        "created_at": "2024-08-12T09:41:43Z",
        "updated_at": "2025-06-12T16:36:44Z",
        "pushed_at": "2024-09-05T11:05:18Z",
        "language": "JavaScript",
        "stargazers_count": 1,
        "forks_count": 0,
        "liveLink": "https://react-windows-11.vercel.app/",
        "image": "/windows.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "Next-JS_Imaginify",
        "full_name": "VrajVyas11/Next-JS_Imaginify",
        "githubLink": "https://github.com/VrajVyas11/Next-JS_Imaginify",
        "description": "Imaginify is a responsive web app that uses Cloudinary AI to transform images with features like restoration, generative fill, object and background removal. It operates on a credit system with secure Stripe payments and Clerk for authentication. Built with React and Next.js, it offers advanced editing in a user-friendly interface.",
        "created_at": "2024-07-29T12:06:54Z",
        "updated_at": "2024-08-10T10:44:51Z",
        "pushed_at": "2024-07-31T11:05:20Z",
        "language": "TypeScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://next-js-imaginify.vercel.app",
        "image": "/imagine.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "easyocr-js",
        "full_name": "VrajVyas11/easyocr-js",
        "githubLink": "https://github.com/VrajVyas11/easyocr-js",
        "description": "easyocr-js is a lightweight wrapper for EasyOCR that enables seamless text recognition in JavaScript. It simplifies integration with EasyOCR's Python backend, allowing developers to perform OCR tasks effortlessly in JS environments.",
        "created_at": "2025-03-07T16:56:21Z",
        "updated_at": "2025-06-12T16:36:33Z",
        "pushed_at": "2025-05-26T15:09:40Z",
        "language": "JavaScript",
        "stargazers_count": 1,
        "forks_count": 0,
        "tags": [
            "easyocr",
            "ocr",
            "optical-character-recognition",
            "wrapper"
        ],
        "liveLink": "https://www.npmjs.com/package/easyocr-js",
        "image": "/easyocr.webp,/easyocr2.jpg",
        "default_branch": "main"
    },
    {
        "title": "AI_Calories_Tracker",
        "full_name": "VrajVyas11/AI_Calories_Tracker",
        "githubLink": "https://github.com/VrajVyas11/AI_Calories_Tracker",
        "description": "AI Calories Tracker lets you snap meals, auto-detect foods via Clarifai, fetch nutrition from USDA, and track calories/macros with a Supabase backend + local persistence. Supports serving adjustments, .env/CI secrets, and an intuitive, lightweight UI.",
        "url": "https://api.github.com/repos/VrajVyas11/AI_Calories_Tracker",
        "created_at": "2025-08-11T10:27:12Z",
        "updated_at": "2025-09-07T10:09:52Z",
        "pushed_at": "2025-09-07T10:09:49Z",
        "language": "Dart",
        "size": 249073,
        "stargazers_count": 3,
        "forks_count": 1,
        "tags": [
            "calories-tracker",
            "clarifai",
            "clarifai-api",
            "dart",
            "flutter",
            "flutter-dotenv",
            "food-recognition",
            "image-recognition",
            "nutrition",
            "usda-national-nutrient-database"
        ],
        "image": "/aicaloriestracker1.png,/aicaloriestracker2.png",
        "default_branch": "main"
    },
    {
        "title": "react-signaturepadcanvas",
        "full_name": "VrajVyas11/react-signaturepadcanvas",
        "githubLink": "https://github.com/VrajVyas11/react-signaturepadcanvas",
        "description": "React Signature Pad Canvas: A customizable React component for capturing signatures. Ideal for forms and contracts, it features adjustable size, theme, and stroke color. Easily integrate it into your app with options to style buttons and container. Supports light and dark themes.",
        "created_at": "2024-09-07T11:47:00Z",
        "updated_at": "2024-09-08T16:40:20Z",
        "pushed_at": "2024-09-08T16:40:17Z",
        "language": "TypeScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://www.npmjs.com/package/react-signaturepadcanvas",
        "image": "/signature.png",
        "tags": [
            "npm",
            "npm-package",
            "react-signaturepadcanvas"
        ],
        "default_branch": "main"
    },
    {
        "title": "Learn_Zustand",
        "full_name": "VrajVyas11/Learn_Zustand",
        "githubLink": "https://github.com/VrajVyas11/Learn_Zustand",
        "description": "A project built with Zustand for state management, enabling dynamic cart functionality with features like adding, removing, and updating product quantities in real time. It fetches user data, integrates a timed joke feature, and uses local storage for persistence. The UI is built using Shadcn components  offering a seamless user experience.",
        "created_at": "2024-10-02T14:15:52Z",
        "updated_at": "2024-10-03T18:23:39Z",
        "pushed_at": "2024-10-02T14:49:27Z",
        "language": "JavaScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://learn-zustand-seven.vercel.app",
        "image": "/zustand.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "Next-js_Socket.ioChatApp",
        "full_name": "VrajVyas11/Next-js_Socket.ioChatApp",
        "githubLink": "https://github.com/VrajVyas11/Next-js_Socket.ioChatApp",
        "description": "A real-time chat application built with Next.js and Socket.io. Features include responsive design, multiple chat rooms, and instant messaging. Utilizes Tailwind CSS for styling and TypeScript for type safety.",
        "created_at": "2024-07-08T10:48:32Z",
        "updated_at": "2024-11-07T09:16:36Z",
        "pushed_at": "2024-11-07T09:16:33Z",
        "language": "TypeScript",
        "stargazers_count": 0,
        "forks_count": 1,
        "liveLink": "https://next-js-socket-iochatapp.onrender.com",
        "image": "/socket.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "Next_JS_Anime_Filter-Scroll",
        "full_name": "VrajVyas11/Next_JS_Anime_Filter-Scroll",
        "githubLink": "https://github.com/VrajVyas11/Next_JS_Anime_Filter-Scroll",
        "description": "A Next.js app showcasing anime with infinite scrolling and smooth transitions using Framer Motion. Features include auto-loading of more animes on scroll and advanced filtering by name, score, kind, status, episodes, and dates. Enjoy a sleek, dynamic experience! ",
        "created_at": "2024-08-11T18:00:29Z",
        "updated_at": "2024-08-11T18:30:07Z",
        "pushed_at": "2024-08-11T18:30:04Z",
        "language": "TypeScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://next-js-anime-filter-scroll.vercel.app",
        "image": "/scroll.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "Next_JS_AUTH_Project",
        "full_name": "VrajVyas11/Next_JS_AUTH_Project",
        "githubLink": "https://github.com/VrajVyas11/Next_JS_AUTH_Project",
        "description": "A Secure Authentication System built with Next.js, Nodemailer, Tailwind CSS, MongoDB, and Mailtrap. Features include secure login, signup, logout, email verification, password reset, token management, and protected routes. Designed with a user-friendly interface.",
        "created_at": "2024-07-03T12:05:49Z",
        "updated_at": "2024-07-10T11:43:47Z",
        "pushed_at": "2024-07-10T11:43:44Z",
        "language": "TypeScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://next-js-auth-project-seven.vercel.app",
        "image": "/nextauth.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "Django_Social_Media_App",
        "full_name": "VrajVyas11/Django_Social_Media_App",
        "githubLink": "https://github.com/VrajVyas11/Django_Social_Media_App",
        "description": "A Django-based social media app for user registration, posting, following, liking, commenting, and profile customization. Features a responsive UI with Tailwind CSS, Bootstrap, and Plain CSS. Includes secure authentication, post management, and user search for an engaging experience.",
        "created_at": "2024-12-29T12:43:52Z",
        "updated_at": "2025-05-08T10:43:51Z",
        "pushed_at": "2025-04-24T11:41:06Z",
        "language": "HTML",
        "stargazers_count": 0,
        "forks_count": 0,
        "tags": [],
        "liveLink": "",
        "image": "/tweet.png",
        "default_branch": "main"
    },
    {
        "title": "Vaadin_Chat_App",
        "full_name": "VrajVyas11/Vaadin_Chat_App",
        "githubLink": "https://github.com/VrajVyas11/Vaadin_Chat_App",
        "description": "Modern Vaadin chat app with group and personal chat, file sharing, and AI (Gemini) integration. Features secure JWT login, Supabase backend for real-time data, and a sleek design. Ideal for collaborative communication with AI assistance.",
        "created_at": "2025-01-18T15:31:56Z",
        "updated_at": "2025-07-08T15:55:55Z",
        "pushed_at": "2025-04-26T04:43:38Z",
        "language": "Java",
        "stargazers_count": 1,
        "forks_count": 3,
        "license": {
            "key": "unlicense",
            "name": "The Unlicense",
            "spdx_id": "Unlicense",
            "url": "https://api.github.com/licenses/unlicense"
        },
        "liveLink": "https://vaadin-chat-app-i7z3.onrender.com",
        "image": "/vaadin.png",
        "tags": [
            "chatapp",
            "chatapplication",
            "chatbot",
            "file-sharing",
            "java",
            "spring-boot",
            "vaadin"
        ],
        "default_branch": "main"
    },
    {
        "title": "Prisma_Supabase_RestFul_Api",
        "full_name": "VrajVyas11/Prisma_Supabase_RestFul_Api",
        "githubLink": "https://github.com/VrajVyas11/Prisma_Supabase_RestFul_Api",
        "description": "Here's your description:  I created a RESTful API in Node.js using Prisma as the ORM and Supabase as the database. The project includes a responsive UI, allowing users to test all the APIs themselves, ensuring a seamless and interactive experience.",
        "created_at": "2024-08-08T21:24:38Z",
        "updated_at": "2024-08-10T10:49:45Z",
        "pushed_at": "2024-08-08T22:08:16Z",
        "language": "HTML",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://prisma-supabase-restful-api.onrender.com",
        "image": "supabase.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "React-Dashboard",
        "full_name": "VrajVyas11/React-Dashboard",
        "githubLink": "https://github.com/VrajVyas11/React-Dashboard",
        "description": "The dashboard features dynamic coloring, integrates Syncfusion for stunning graphs, and boasts a fully responsive UI with high-grade design. With dynamic elements, the dashboard provides an interactive and visually appealing experience, making data visualization both effective and engaging.",
        "created_at": "2024-08-03T10:15:08Z",
        "updated_at": "2024-08-10T10:47:28Z",
        "pushed_at": "2024-08-03T10:25:46Z",
        "language": "JavaScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "",
        "image": "",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "React_Native-QuizApp",
        "full_name": "VrajVyas11/React_Native-QuizApp",
        "githubLink": "https://github.com/VrajVyas11/React_Native-QuizApp",
        "description": "a react native app that is Quiz of 10 Questions after answering all you will get your score ...the genre of questions are diverse so the user will new and unique questions every time ",
        "created_at": "2024-06-19T10:13:00Z",
        "updated_at": "2024-06-19T10:48:30Z",
        "pushed_at": "2024-06-19T10:48:27Z",
        "language": "JavaScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "",
        "image": "quiz.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "React_Native-RollTheDice",
        "full_name": "VrajVyas11/React_Native-RollTheDice",
        "githubLink": "https://github.com/VrajVyas11/React_Native-RollTheDice",
        "description": "A simple app that rolls a dice and returns a random dice side to the user ",
        "created_at": "2024-06-19T10:34:39Z",
        "updated_at": "2024-06-19T10:49:12Z",
        "pushed_at": "2024-06-19T10:49:08Z",
        "language": "TypeScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "",
        "image": "/dice.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "React_Native-TicTacToe",
        "full_name": "VrajVyas11/React_Native-TicTacToe",
        "githubLink": "https://github.com/VrajVyas11/React_Native-TicTacToe",
        "description": "It is a simple TicTacToe game made in React Native with minimal Design and Robust Logic ",
        "created_at": "2024-06-19T10:25:23Z",
        "updated_at": "2024-06-19T10:33:04Z",
        "pushed_at": "2024-06-19T10:33:01Z",
        "language": "TypeScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "",
        "image": "/tictactoe.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "React_Native-Voiced_AI_Chat_Image_Bot",
        "full_name": "VrajVyas11/React_Native-Voiced_AI_Chat_Image_Bot",
        "githubLink": "https://github.com/VrajVyas11/React_Native-Voiced_AI_Chat_Image_Bot",
        "description": "An app that is used for chat responses (the same as chatGPT) and also can generate Images (the same as Dall E), on top of which i reads response with ai voice",
        "created_at": "2024-06-18T09:46:58Z",
        "updated_at": "2025-06-12T16:36:54Z",
        "pushed_at": "2024-06-20T10:50:35Z",
        "language": "JavaScript",
        "stargazers_count": 1,
        "forks_count": 0,
        "liveLink": "",
        "image": "Chatbot.png",
        "tags": [],
        "default_branch": "main"
    },
    {
        "title": "REACT_PWA_Drawboard",
        "full_name": "VrajVyas11/REACT_PWA_Drawboard",
        "githubLink": "https://github.com/VrajVyas11/REACT_PWA_Drawboard",
        "description": "\"REACT_PWA_Drawboard\" is a progressive web app (PWA) built with React, integrating @tldraw for collaborative drawing. It features real-time drawing capabilities and utilizes modern PWA principles for offline use and installation on devices.",
        "created_at": "2024-07-10T12:25:38Z",
        "updated_at": "2024-07-14T11:29:26Z",
        "pushed_at": "2024-07-14T11:29:23Z",
        "language": "JavaScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://react-pwa-drawboard.vercel.app",
        "image": "/pwa.png",
        "tags": [],
        "default_branch": "main"
    },

    {
        "title": "Redis_Rate_Limiting_API",
        "full_name": "VrajVyas11/Redis_Rate_Limiting_API",
        "githubLink": "https://github.com/VrajVyas11/Redis_Rate_Limiting_API",
        "description": "This project demonstrates rate limiting and caching with Redis in a Node.js + Express API. It includes Docker containerization and features routes for product data and order placement. The API uses Redis to optimize performance and prevent overloading. Explore the live demo or contribute by following the setup instructions.",
        "created_at": "2024-08-23T12:29:37Z",
        "updated_at": "2024-09-05T08:03:55Z",
        "pushed_at": "2024-09-05T08:01:55Z",
        "language": "JavaScript",
        "stargazers_count": 0,
        "forks_count": 0,
        "liveLink": "https://redis-rate-limiting-api.onrender.com/",
        "image": "redis.png",
        "tags": [],
        "default_branch": "main"
    }
]

export default projects